name: Integration Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automatic requirements.txt for Python Project
        uses: ryan-rozario/pipreqs-action@master
